Repository GluuFederation/cloud-native-edition, pull requests merged in 2020-11, with the labels that each got.

#239 Enhance wizard steps flexibility and adding stop control for installation
  pygluu/kubernetes/gui/app.py
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/templates/base.html
  pygluu/kubernetes/gui/templates/forms.html
  pygluu/kubernetes/gui/templates/index.html
  pygluu/kubernetes/gui/templates/installation.html
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/operation.py
  pygluu/kubernetes/gui/views/wizard.py
Labels: enhancement

#247 feat(validate-settings): Add settings validation before installing
  pygluu/kubernetes/create.py
  pygluu/kubernetes/gui/templates/preinstall.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/settings.py
  settings_schema.json
  setup.py
Labels: 5.0, CLI, GUI, enhancement

#248 fix(settings-validation): fix schema condition logic
  settings_schema.json
Labels: 5.0, CLI, GUI, bug

#249 fix(settings-validation): Initiate settings and fix typo
  pygluu/kubernetes/create.py
  settings_schema.json
Labels: 5.0, GUI, bug

#260 test(test_settings): Improve test cases for settings module
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/settings.py
  tests/test_settings.py
Labels: 5.0, enhancement

#261 fix(settings-validation): typo, and remove duplicate properties
  pygluu/kubernetes/gui/forms/replicas.py
  pygluu/kubernetes/gui/views/wizard.py
  settings_schema.json
Labels: 5.0, bug
