Repository GluuFederation/cloud-native-edition, pull requests merged in 2020-09, with the labels that each got.

#167 Add support for alb ingress with pygluu helm install
  pygluu/kubernetes/helm.py
  pygluu/kubernetes/kustomize.py
  pygluu/kubernetes/templates/README.md
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu-upgrade/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/casa/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/casa/templates/service.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/fido2/templates/service.yml
  pygluu/kubernetes/templates/helm/gluu/charts/gluu-istio-ingress/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxauth/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/charts/oxauth/templates/service.yml
  pygluu/kubernetes/templates/helm/gluu/charts/oxpassport/templates/service.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxshibboleth/templates/service.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxtrust/templates/service.yml
  pygluu/kubernetes/templates/helm/gluu/charts/radius/templates/service.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/scim/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/scim/templates/service.yml
  pygluu/kubernetes/templates/helm/gluu/values.yaml
  pygluu/kubernetes/templates/oxauth/base/deployments.yaml
  pygluu/kubernetes/terminal/helm.py
Labels: enhancement

#174 Enhancements and fixes
  pygluu/kubernetes/gui/app.py
  pygluu/kubernetes/gui/config.py
  pygluu/kubernetes/gui/forms/configuration.py
  pygluu/kubernetes/gui/forms/couchbase.py
  pygluu/kubernetes/gui/forms/gluugateway.py
  pygluu/kubernetes/gui/forms/helm.py
  pygluu/kubernetes/gui/forms/helpers.py
  pygluu/kubernetes/gui/forms/jackrabbit.py
  pygluu/kubernetes/gui/forms/postgres.py
  pygluu/kubernetes/gui/forms/upgrade.py
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/static/css/styles.css
  pygluu/kubernetes/gui/static/img/amazon-eks.svg
  pygluu/kubernetes/gui/static/img/azure-aks.svg
  pygluu/kubernetes/gui/static/img/digital-ocean.svg
  pygluu/kubernetes/gui/static/img/google-gke.svg
  pygluu/kubernetes/gui/static/img/kubernetes.svg
  pygluu/kubernetes/gui/static/img/microk8s.svg
  pygluu/kubernetes/gui/static/img/minikube.svg
  pygluu/kubernetes/gui/templates/forms.html
  pygluu/kubernetes/gui/templates/index.html
  pygluu/kubernetes/gui/templates/install/kustomize.html
  pygluu/kubernetes/gui/templates/wizard/deployment_arch.html
  pygluu/kubernetes/gui/templates/wizard/gluu_gateway.html
  pygluu/kubernetes/gui/templates/wizard/helm.html
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/templates/wizard/install_jackrabbit.html
  pygluu/kubernetes/gui/templates/wizard/upgrade.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  pygluu/kubernetes/settings.py
Labels: enhancement

#180 Fix Couchbase sudden death in GUI install. Fix Multiple bug report in gui installation paths and add gunicorn
  pygluu/kubernetes/gui/app.py
  pygluu/kubernetes/gui/forms/couchbase.py
  pygluu/kubernetes/gui/forms/istio.py
  pygluu/kubernetes/gui/forms/volumes.py
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/templates/forms.html
  pygluu/kubernetes/gui/templates/installation.html
  pygluu/kubernetes/gui/templates/wizard/environment.html
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/templates/wizard/install_istio.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  setup.py
  tests/gui/test_app.py
  tox.ini
Labels: GUI

#189 Add Couchbase superuser and password to GUI install
  pygluu/kubernetes/gui/forms/couchbase.py
  pygluu/kubernetes/gui/templates/wizard/couchbase.html
  pygluu/kubernetes/gui/views/wizard.py
Labels: bug

#194 add debug/development mode option
  pygluu/kubernetes/gui/app.py
Labels: enhancement

#192 Hide optional volume type on cloud deployments if host volume is used
  pygluu/kubernetes/gui/forms/helpers.py
  pygluu/kubernetes/gui/forms/volumes.py
  pygluu/kubernetes/gui/templates/wizard/app_volume_type.html
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/views/wizard.py
Labels: enhancement

#196 Hide istio injection when istio ingress is enabled.
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/templates/wizard/install_istio.html
  pygluu/kubernetes/gui/views/wizard.py
Labels: bug, enhancement
