Repository GluuFederation/cloud-native-edition, pull requests merged in 2020-10, with the labels that each got.

#198 Direct installation actions to wizard.
  pygluu/kubernetes/gui/app.py
  pygluu/kubernetes/gui/views/main.py
  tests/gui/test_app.py
Labels: enhancement

#205 Added settings.json file upload feature in installation option
  pygluu/kubernetes/gui/config.py
  pygluu/kubernetes/gui/static/js/notify.min.js
  pygluu/kubernetes/gui/templates/base.html
  pygluu/kubernetes/gui/templates/forms.html
  pygluu/kubernetes/gui/templates/index.html
  pygluu/kubernetes/gui/templates/preinstall.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  pygluu/kubernetes/templates/gluu_versions.json
Labels: enhancement

#215 Add custom extension for SettingsHandler on flask app, to avoid race condition between app modules
  pygluu/kubernetes/gui/app.py
  pygluu/kubernetes/gui/extensions.py
  pygluu/kubernetes/gui/forms/configuration.py
  pygluu/kubernetes/gui/forms/images.py
  pygluu/kubernetes/gui/forms/volumes.py
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/templates/wizard/app_volume_type.html
  pygluu/kubernetes/gui/templates/wizard/config.html
  pygluu/kubernetes/gui/templates/wizard/environment.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  pygluu/kubernetes/settings.py
Labels: GUI, bug

#222 chore: Upgrade actions-setup-minikube to v2.0.1
  .github/workflows/minikube.yml
Labels: enhancement

#227 CLI: show image prompt after selecting upgrade version
  pygluu/kubernetes/terminal/upgrade.py
  tests/terminal/test_upgrade.py
Labels: bug, enhancement

#225 Fix overwriting of custom image names when upgrading
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/views/wizard.py
Labels: GUI, bug

#229 Wizard form enhancements
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/views/wizard.py
Labels: GUI, enhancement
