Repository GluuFederation/cloud-native-edition, pull requests merged in 2021-05, with the labels that each got.

#309 refactor(4.3): prepare branch 4.3
  .github/workflows/microk8s.yml
  pygluu/kubernetes/create.py
  pygluu/kubernetes/gui/forms/gluugateway.py
  pygluu/kubernetes/gui/forms/helm.py
  pygluu/kubernetes/gui/forms/images.py
  pygluu/kubernetes/gui/forms/postgres.py
  pygluu/kubernetes/gui/forms/redis.py
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/installer.py
  pygluu/kubernetes/gui/templates/index.html
  pygluu/kubernetes/gui/templates/wizard/cache_type.html
  pygluu/kubernetes/gui/templates/wizard/gluu_gateway.html
  pygluu/kubernetes/gui/templates/wizard/helm.html
  pygluu/kubernetes/gui/templates/wizard/index.html
  pygluu/kubernetes/gui/templates/wizard/install_jackrabbit.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  pygluu/kubernetes/helm.py
  pygluu/kubernetes/kustomize.py
  pygluu/kubernetes/postgres.py
  pygluu/kubernetes/redis.py
  pygluu/kubernetes/settings.py
  pygluu/kubernetes/templates/README.md
  pygluu/kubernetes/templates/alb/ingress.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/base/deployments.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/base/ingress.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/base/jobs.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/base/kustomization.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/base/services.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/kong-all-in-one-db.yaml
  pygluu/kubernetes/templates/gluu-gateway-ui/kong-init-job.yaml
  pygluu/kubernetes/templates/gluu_versions.json
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/.helmignore
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/_helpers.tpl
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/configmaps.yml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/ingress.yaml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/jobs.yaml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/secrets.yml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/templates/service.yml
  pygluu/kubernetes/templates/helm/gluu-gateway-ui/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxd-server/templates/networkpolicy.yaml
  pygluu/kubernetes/templates/oxd-server/base/networkpolicy.yaml
  pygluu/kubernetes/templates/postgres/postgres.yaml
  pygluu/kubernetes/templates/postgres/storageclasses.yaml
  pygluu/kubernetes/templates/redis/configmaps.yaml
  pygluu/kubernetes/templates/redis/redis.yaml
  pygluu/kubernetes/templates/redis/storageclasses.yaml
  pygluu/kubernetes/terminal/confirmsettings.py
  pygluu/kubernetes/terminal/gluugateway.py
  pygluu/kubernetes/terminal/helm.py
  pygluu/kubernetes/terminal/images.py
  pygluu/kubernetes/terminal/postgres.py
  pygluu/kubernetes/terminal/prompt.py
  pygluu/kubernetes/terminal/redis.py
  setup.py
Labels: 4.3, CLI, GUI, enhancement

#315 chore: release 1.5.0
  CHANGELOG.md
  pygluu/kubernetes/version.py
Labels: autorelease: pending

#317 feat: add support for ob transport key and cert pksc12 generation
  pygluu/kubernetes/templates/helm/gluu-5.0.0.tgz
  pygluu/kubernetes/templates/helm/gluu/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/auth-server/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/configmaps.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/secrets.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/values.yaml
  pygluu/kubernetes/templates/helm/gluu/openbanking-values.yaml
  pygluu/kubernetes/templates/helm/gluu/values.schema.json
  pygluu/kubernetes/templates/helm/gluu/values.yaml
  pygluu/kubernetes/templates/helm/index.yaml
Labels: 5.0, enhancement

#318 chore: release openbanking distribution
  pygluu/kubernetes/templates/helm/gluu-5.0.0.tgz
  pygluu/kubernetes/templates/helm/gluu/Chart.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/auth-server-key-rotation/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/auth-server/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/charts/auth-server/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/client-api/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config-api/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/secrets.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/fido2/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/persistence/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/scim/values.yaml
  pygluu/kubernetes/templates/helm/gluu/openbanking-values.yaml
  pygluu/kubernetes/templates/helm/gluu/values.schema.json
  pygluu/kubernetes/templates/helm/gluu/values.yaml
  pygluu/kubernetes/templates/helm/index.yaml
Labels: 5.0, enhancement

#319 chore: release 1.5.1
  CHANGELOG.md
  pygluu/kubernetes/version.py
Labels: autorelease: pending

#323 chore: release 1.5.2
  CHANGELOG.md
  pygluu/kubernetes/version.py
Labels: autorelease: pending

#327 chore: release 1.5.3
  CHANGELOG.md
  pygluu/kubernetes/version.py
Labels: autorelease: pending

#321 feat: add spanner and google secret support
  pygluu/kubernetes/gui/forms/persistencebackend.py
  pygluu/kubernetes/gui/forms/spanner.py
  pygluu/kubernetes/gui/helpers.py
  pygluu/kubernetes/gui/templates/wizard/spanner.html
  pygluu/kubernetes/gui/views/main.py
  pygluu/kubernetes/gui/views/wizard.py
  pygluu/kubernetes/helm.py
  pygluu/kubernetes/settings.py
  pygluu/kubernetes/templates/helm/gluu/charts/casa/templates/deployment.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/configmaps.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/load-init-config.yml
  pygluu/kubernetes/templates/helm/gluu/charts/config/templates/secrets.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/config/values.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/fido2/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/charts/opendj/templates/statefulset.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxauth-key-rotation/templates/cronjobs.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxauth/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/charts/oxd-server/templates/deployment.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxpassport/templates/deployment.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxshibboleth/templates/statefulset.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/oxtrust/templates/statefulset.yml
  pygluu/kubernetes/templates/helm/gluu/charts/persistence/templates/jobs.yml
  pygluu/kubernetes/templates/helm/gluu/charts/radius/templates/deployment.yaml
  pygluu/kubernetes/templates/helm/gluu/charts/scim/templates/deployment.yml
  pygluu/kubernetes/templates/helm/gluu/values.yaml
  pygluu/kubernetes/terminal/persistencebackend.py
  pygluu/kubernetes/terminal/prompt.py
  pygluu/kubernetes/terminal/spanner.py
Labels: 4.3, enhancement

#329 chore: release 1.5.5
  CHANGELOG.md
  pygluu/kubernetes/version.py
Labels: autorelease: pending
